### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Benefit-Zebra** [I-Am-The-Great/BS-mods#1]
@I-Am-The-Great 
I don't wanted to create this issue as it is 
not related to repository but since your mobile is with your father,I can't whatsapp.

So, on Discord I tried to rob @Taha and it was successful and then he messaged me,

![Screenshot_2019-04-01-13-14-25](https://user-images.githubusercontent.com/42458260/55311890-ce4a4900-5481-11e9-9349-53c81eefb382.png)

@Taha has also tried to rob persons

![Screenshot_2019-04-01-13-24-38](https://user-images.githubusercontent.com/42458260/55311989-06518c00-5482-11e9-97b8-6afa540c9218.png)

![Screenshot_2019-04-01-13-24-55](https://user-images.githubusercontent.com/42458260/55312006-0fdaf400-5482-11e9-8756-5ab5a01651d0.png)

What should I do now of his message?

**Comment by I-Am-The-Great** [comment]
@Benefit-Zebra, by the way, it is not the correct place to talk about discord issue, but I can understand why you did this, anyway no problem with it, and sorry I am seeing this message after 20 hours approx because I have been very busy yesterday in fixing my laptop that I did not get time to come online on discord or anywhere.
Well, now lets come to the topic, I think you should just ignore him, you did nothing wrong because robbing is a part of playing using that bot in discord, and if he abuses you or criticize you or say anything wrong about you in the `Gaming Loverz!!!` discord server, then report the incident with a screenshot in the `complaints` channel, and we leaders of the server will take necessary action.

**Comment by Benefit-Zebra** [comment]
@I-Am-The-Great

Thanks and I will inform you If he again messages me like this.Also I have created a repository named "Talkies" Where If I have something unrelated to topic, We can talk there.

As I earlier said, "I didn't wanted to create this issue as it is not related to repository but since your mobile is with your father,I can't whatsapp." So sorry

Now I am closing this issue.
